# Generated by Django 3.1 on 2020-09-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_auto_20200921_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_methods',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
