# Generated by Django 3.1 on 2020-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_auto_20200921_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_methods',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
