# Generated by Django 3.1 on 2020-09-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_auto_20200922_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery_methods',
            options={'ordering': ('delivery_method',), 'verbose_name': 'Delivery Method', 'verbose_name_plural': 'Delivery Methods'},
        ),
    ]
