# Generated by Django 3.1.2 on 2020-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(blank=True, default='0', max_length=15, null=True, unique=True, verbose_name='Tax Payer Number'),
        ),
    ]
