# Generated by Django 3.1 on 2020-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0002_auto_20200903_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
