# Generated by Django 3.1.2 on 2020-10-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201014_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Tax Payer Number'),
        ),
    ]
