# Generated by Django 3.1 on 2020-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_customers_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user_permissions',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
    ]
