# Generated by Django 3.1.2 on 2020-10-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201014_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='stripe_customer',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
