# Generated by Django 3.1 on 2020-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customers_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='ein_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Employer Identification Number'),
        ),
    ]
