# Generated by Django 3.1 on 2020-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200904_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Employer Identification Number'),
        ),
    ]
