# Generated by Django 3.1 on 2020-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200904_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(default=111111111, max_length=9, verbose_name='Employer Identification Number'),
        ),
    ]
