# Generated by Django 3.1 on 2020-09-04 19:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200904_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='123256575', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tax Payer Number'),
        ),
    ]
