# Generated by Django 3.1 on 2020-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200904_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein_verified',
            field=models.BooleanField(default=False, verbose_name='Tax Payer Number Verified?'),
        ),
    ]
