# Generated by Django 3.1 on 2020-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200904_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('date_joined',), 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=70, unique=True, verbose_name='email'),
        ),
    ]
