# Generated by Django 3.1 on 2020-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200904_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Tax Payer Number'),
        ),
    ]
