# Generated by Django 3.1 on 2020-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200904_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='ein_verified',
            field=models.BooleanField(default=False, verbose_name='TPN Verified?'),
        ),
    ]
