# Generated by Django 3.1 on 2020-09-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='categories/%Y/%m/%d'),
        ),
    ]
