# Generated by Django 3.1 on 2020-09-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variation_variationmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='category',
            new_name='categories',
        ),
    ]
