# Generated by Django 3.1 on 2020-09-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200930_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
