# Generated by Django 3.1 on 2020-09-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_variation_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='cost',
        ),
    ]
