# Generated by Django 3.1 on 2020-10-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200930_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='sku',
        ),
    ]
