# Generated by Django 3.1 on 2020-10-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_attribute_attributebase_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
    ]
