# Generated by Django 3.1 on 2020-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='amount_from',
            field=models.PositiveIntegerField(help_text='bigger than or equals to', unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='amount_to',
            field=models.PositiveIntegerField(help_text='bigger than or equals to', unique=True),
        ),
    ]
