# Generated by Django 3.1.2 on 2020-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20201013_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
