# Generated by Django 3.1.2 on 2020-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20201013_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
