# Generated by Django 3.1.2 on 2020-10-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20201013_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='blinking_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
