# Generated by Django 3.1.2 on 2021-03-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0002_source_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
