# Generated by Django 3.1.7 on 2021-04-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0004_archivedinventorylog_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ship_station.product'),
        ),
    ]
