# Generated by Django 3.1.2 on 2021-03-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
