# Generated by Django 3.1.7 on 2021-04-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0005_auto_20210421_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, help_text='.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ship_station.model'),
        ),
    ]
