# Generated by Django 3.1.7 on 2021-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0007_auto_20210421_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='note',
            field=models.CharField(help_text='type your notes here about this item', max_length=120, null=True),
        ),
    ]
