# Generated by Django 3.1.7 on 2021-04-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0005_auto_20210420_0054'),
        ('ship_station', '0009_auto_20210421_1147'),
    ]

    operations = [
    ]
