# Generated by Django 3.1.7 on 2021-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0010_auto_20210423_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
