# Generated by Django 3.1.7 on 2021-04-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0010_merge_20210421_1225'),
        ('ship_station', '0010_auto_20210423_0012'),
    ]

    operations = [
    ]
