# Generated by Django 3.1.7 on 2021-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0011_auto_20210423_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
