# Generated by Django 3.1.7 on 2021-04-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0012_product_ean2'),
        ('ship_station', '0012_merge_20210423_0040'),
    ]

    operations = [
    ]
