# Generated by Django 3.1.7 on 2021-04-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0013_auto_20210423_1014'),
        ('ship_station', '0013_merge_20210423_0043'),
    ]

    operations = [
    ]
