# Generated by Django 3.1.7 on 2021-04-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0014_merge_20210423_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='colorCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='styleID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='caseQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skuID_Master',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='sizeCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
