# Generated by Django 3.1.7 on 2021-04-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0015_auto_20210425_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ean',
            new_name='gtin',
        ),
    ]
