# Generated by Django 3.1.7 on 2021-04-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0017_auto_20210425_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ean2',
        ),
    ]
