# Generated by Django 3.1.7 on 2021-04-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0018_remove_product_ean2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='skuID_Master',
        ),
    ]
