# Generated by Django 3.1.7 on 2021-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_station', '0019_auto_20210425_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='colorCode',
            field=models.CharField(max_length=100),
        ),
    ]
