# Generated by Django 3.1 on 2020-09-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200908_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
