# Generated by Django 3.1 on 2020-09-12 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200912_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaign_discount',
            field=models.IntegerField(default=0, help_text='Discount by percentage. Maximum 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
