# Generated by Django 3.1 on 2020-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200915_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='campaign_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_amount',
            field=models.IntegerField(default=0),
        ),
    ]
