# Generated by Django 3.1 on 2020-09-18 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_campaign_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaign_discount',
            field=models.IntegerField(default=0, help_text='Discount by percentage. Maximum 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
