# Generated by Django 3.1 on 2020-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200919_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('LOCALPICKUP', 'Local Pickup'), ('LOCALDELIVERY', 'Local Delivery')], max_length=50),
        ),
    ]
