# Generated by Django 3.1 on 2020-09-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Company_name',
            new_name='company_name',
        ),
    ]
