# Generated by Django 3.1.2 on 2020-10-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201012_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(max_length=50),
        ),
    ]
