# Generated by Django 3.1.2 on 2020-10-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201012_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
