# Generated by Django 3.1 on 2020-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_order_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
