# Generated by Django 3.1 on 2020-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit_margin',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
    ]
