# Generated by Django 3.1 on 2020-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200909_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit_margin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
