# Generated by Django 3.1 on 2020-09-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='coupon_discount',
        ),
    ]
