# Generated by Django 3.1 on 2020-09-12 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_campaign'),
        ('orders', '0018_auto_20200912_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='campaign_discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
