# Generated by Django 3.1 on 2020-09-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200921_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fees',
            field=models.IntegerField(default=0),
        ),
    ]
