# Generated by Django 3.1 on 2020-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
