# Generated by Django 3.1.2 on 2020-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201026_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(help_text='SKU must be unique', max_length=60, unique=True),
        ),
    ]
