# Generated by Django 3.1 on 2020-10-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201001_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='cost',
        ),
    ]
