# Generated by Django 3.1 on 2020-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
