# Generated by Django 3.1.2 on 2020-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201026_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='clearance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
