# Generated by Django 3.1 on 2020-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variation_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
