# Generated by Django 3.1.2 on 2020-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201026_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='clearance',
            field=models.BooleanField(default=False),
        ),
    ]
