# Generated by Django 3.1.2 on 2020-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201002_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_slug',
        ),
    ]
