# Generated by Django 3.1.2 on 2020-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_category_parent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', help_text='System may give an error if category the image does not exist', upload_to='categories/%Y/%m/%d'),
        ),
    ]
