# Generated by Django 3.1.2 on 2020-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', upload_to='products/%Y/%m/%d'),
        ),
    ]
