# Generated by Django 3.1.2 on 2020-10-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201027_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
    ]
