# Generated by Django 3.1 on 2020-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_variation_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
