# Generated by Django 3.1.2 on 2020-10-27 19:49

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=quilljs.fields.RichTextField(blank=True, null=True),
        ),
    ]
