# Generated by Django 3.1 on 2020-09-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_variationmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
