# Generated by Django 3.1 on 2020-09-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200930_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='sale_price',
        ),
    ]
