# Generated by Django 3.1.2 on 2020-10-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201009_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ForeignKey(blank=True, default='img/no_image.png', on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
        ),
    ]
