# Generated by Django 3.1.2 on 2020-10-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20201027_1444'),
        ('products', '0027_remove_product_content'),
    ]

    operations = [
    ]
