# Generated by Django 3.1.2 on 2020-10-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_merge_20201027_1825'),
        ('products', '0028_remove_variation_clearance'),
    ]

    operations = [
    ]
