# Generated by Django 3.1.2 on 2020-10-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201009_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='available',
        ),
    ]
