# Generated by Django 3.1.2 on 2020-10-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201009_1732'),
        ('products', '0013_auto_20201008_1410'),
    ]

    operations = [
    ]
