# Generated by Django 3.1.2 on 2020-10-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_merge_20201028_1006'),
        ('products', '0030_auto_20201030_1644'),
    ]

    operations = [
    ]
