# Generated by Django 3.1.2 on 2020-10-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_merge_20201009_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='img/no_image.png', help_text='System may give an error if the category image does not exist', upload_to='categories/%Y/%m/%d'),
        ),
    ]
