# Generated by Django 3.1.2 on 2020-10-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20201009_1738'),
        ('products', '0031_auto_20201009_1743'),
    ]

    operations = [
    ]
