# Generated by Django 3.1.2 on 2020-11-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20201102_1551'),
        ('products', '0034_auto_20201102_1552'),
    ]

    operations = [
    ]
