# Generated by Django 3.1.2 on 2020-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_merge_20201102_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/logo.png', help_text='System may give an error if product cover image does not exist', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
